http://dados.gov.br/dataset/indice-de-reclamacoes
    
O IGR têm como base os dados de beneficiários e reclamações recebidos pela ANS e permitem comparar a atuação das empresas que atuam no setor de Saúde Suplementar.

Gráficos, Link abaixo:

http://www.ans.gov.br/planos-de-saude-e-operadoras/informacoes-e-avaliacoes-de-operadoras/indice-de-reclamacoes/indice-geral-de-reclamacoes-igr
    
Tem como principal finalidade apresentar um termômetro do comportamento das operadoras do setor no atendimento aos problemas apontados pelos beneficiários. Contempla o número médio de reclamações de beneficiários recebidas nos três meses anteriores e classificadas até a data de extração do dado. O índice tem como referência cada 10.000 beneficiários do universo de consumidores analisado.

In [1]:
import pandas as pd

In [3]:
igr = pd.read_csv("CSV/igr_anual_csv/igr.csv", sep=';', encoding='UTF-8')
igr2015 = pd.read_csv("CSV/igr_anual_csv/IGR_2015.csv", sep=';', encoding='ISO-8859-1')
igr2016 = pd.read_csv("CSV/igr_anual_csv/IGR_2016.csv", sep=';', encoding='ISO-8859-1')
igr2017 = pd.read_csv("CSV/igr_anual_csv/IGR_2017.csv", sep=';', encoding='ISO-8859-1')
igr2018 = pd.read_csv("CSV/igr_anual_csv/IGR_2018.csv", sep=';', encoding='ISO-8859-1')

In [4]:
igr.head()

,Raz�o Social (Registro ANS),Cobertura,Porte,Classifica��o no M�s,Classifica��o no M�s Anterior,set/19,ago/19,jul/19,jun/19,mai/19,abr/19,mar/19,fev/19,jan/19,dez/18,nov/18,out/18,Compet�ncia,Data de atualiza��o
0,ABERTTA SA�DE - ASSOCIA��O BENEFICENTE DOS EMP...,M�dico Hospitalar,M�dio,211,220.0,"0,27","0,27","0,27","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00",201909,12/10/2019 19:45:32
1,ADVANCE PLANOS DE SA�DE LTDA (335657),M�dico Hospitalar,Pequeno,47,29.0,"6,89","17,08","10,16","23,55","13,37","19,91","6,59","6,53","3,24","9,67","12,82","15,93",201909,12/10/2019 19:45:32
2,AGEMED SA�DE S.A. (339601),M�dico Hospitalar,Grande,1,2.0,"36,15","32,32","28,35","29,35","28,83","25,45","18,96","13,18","10,60","8,50","7,30","5,46",201909,12/10/2019 19:45:32
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,M�dico Hospitalar,Pequeno,176,189.0,"0,64","0,64","1,27","2,54","2,53","1,90","0,00","0,63","0,63","1,26","0,63","0,63",201909,12/10/2019 19:45:32
4,ALCANCE SA�DE LTDA. (416975),M�dico Hospitalar,Pequeno,185,197.0,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00",201909,12/10/2019 19:45:32

In [20]:
igr2015.head()

,Razão Social (Registro ANS),Cobertura,Porte,Classificação no Mês,Classificação no Mês Anterior,dez/15,nov/15,out/15,set/15,ago/15,jul/15,jun/15,mai/15,abr/15,mar/15,fev/15,jan/15,Competência,Data de atualização
0,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,Médico Hospitalar,Pequeno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"100,00","100,00","100,00","100,00",201512,22/01/2016 16:40:35
1,ADVANCE PLANOS DE SAÚDE LTDA (335657),Médico Hospitalar,Pequeno,97.0,113.0,"80,00","66,67","42,86","0,00","0,00",NaN,"100,00","100,00","66,67","33,33","0,00","25,00",201512,22/01/2016 16:40:35
2,AGEMED SAÚDE S.A. (339601),Médico Hospitalar,Grande,69.0,76.0,"92,31","84,21","85,19","76,67","78,26","66,67","100,00","63,64","68,75","73,68","85,71","88,89",201512,22/01/2016 16:40:35
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,Médico Hospitalar,Pequeno,NaN,NaN,NaN,NaN,"100,00","100,00","100,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,201512,22/01/2016 16:40:35
4,ALLIANZ SAÚDE S/A (000515),Médico Hospitalar,Médio,1.0,1.0,"100,00","100,00","95,00","96,77","96,67","100,00","100,00","100,00","93,94","82,35","77,14","75,61",201512,22/01/2016 16:40:35

In [21]:
igr2016.head()

,RazÃ£o Social (Registro ANS),Cobertura,Porte,ClassificaÃ§Ã£o no MÃªs,ClassificaÃ§Ã£o no MÃªs Anterior,dez/16,nov/16,out/16,set/16,ago/16,jul/16,jun/16,mai/16,abr/16,mar/16,fev/16,jan/16,CompetÃªncia,Data de atualizaÃ§Ã£o
0,ABERTTA SAÃDE - ASSOCIAÃÃO BENEFICENTE DOS ...,MÃ©dico Hospitalar,Pequeno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201612,22/01/2017 02:12:18
1,ADVANCE PLANOS DE SAÃDE LTDA (335657),MÃ©dico Hospitalar,Pequeno,1.0,1.0,"100,00","100,00","66,67","37,50","30,00","16,67","33,33","80,00","60,00","60,00","33,33","50,00",201612,22/01/2017 02:12:18
2,AGEMED SAÃDE S.A. (339601),MÃ©dico Hospitalar,Grande,72.0,72.0,"85,00","75,00","65,79","69,05","76,92","86,67","79,31","79,31","78,57","80,95","63,16","52,63",201612,22/01/2017 02:12:18
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,MÃ©dico Hospitalar,Pequeno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201612,22/01/2017 02:12:18
4,ALLIANZ SAÃDE S/A (000515),MÃ©dico Hospitalar,MÃ©dio,1.0,1.0,"100,00","100,00","100,00","100,00","100,00","100,00","90,91","92,31","84,62","94,12","94,44","100,00",201612,22/01/2017 02:12:18

In [119]:
igr2017.head()

,Razão Social (Registro ANS),Cobertura,Porte,Classificação no Mês,Classificação no Mês Anterior,dez/17,nov/17,out/17,set/17,ago/17,jul/17,jun/17,mai/17,abr/17,mar/17,fev/17,jan/17,Competência,Data de atualização
0,ABERTTA SAÚDE - ASSOCIAÇÃO BENEFICENTE DOS EMP...,Médico Hospitalar,Médio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201712,05/02/2018 11:09:28
1,ADVANCE PLANOS DE SAÚDE LTDA (335657),Médico Hospitalar,Pequeno,NaN,1.0,NaN,"100,00","100,00","100,00","100,00","100,00",NaN,NaN,"100,00","100,00","100,00","100,00",201712,05/02/2018 11:09:28
2,AGEMED SAÚDE S.A. (339601),Médico Hospitalar,Grande,74.0,77.0,"79,55","72,73","73,58","83,33","93,33","89,58","92,86","89,13","81,40","69,70","52,17","57,69",201712,05/02/2018 11:09:28
3,AGROS - INSTITUTO UFV DE SEGURIDADE SOCIAL (36...,Médico Hospitalar,Pequeno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201712,05/02/2018 11:09:28
4,ALLIANZ SAÚDE S/A (000515),Médico Hospitalar,Médio,135.0,155.0,"92,00","84,62","82,14","83,87","86,84","90,00","85,71","89,13","89,13","89,74","87,10","85,71",201712,05/02/2018 11:09:28